/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /v1/batches` — create a batch from a list of items.
         * @description Budget and rate limits are enforced up front with the **same** check the
         *     interactive turn paths use ([`crate::v1::enforce_limits`]), so a tenant whose
         *     budget action is `block` cannot bypass the block by submitting work as a
         *     batch. The rate-limit check counts a batch create as a **single** request
         *     (not one per item); the budget block is the primary guard against a large
         *     batch running up spend past a hard cap.
         */
        post: operations["create_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/batches/{id}` — the batch's status and counts. */
        get: operations["get_batch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/batches/{id}/cancel` — request cancellation of a batch. */
        post: operations["cancel_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /v1/batches/{id}/results` — the per-item results as streamed JSONL
         *     (one `{custom_id, status, result}` object per line).
         */
        get: operations["get_batch_results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/conversations` — create a tenant-scoped conversation. */
        post: operations["create_conversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /v1/conversations/{id}` — fetch a conversation with a page of its
         *     history, scoped to the caller's tenant.
         */
        get: operations["get_conversation"];
        put?: never;
        post?: never;
        /**
         * `DELETE /v1/conversations/{id}` — delete a conversation scoped to the
         *     caller's tenant.
         */
        delete: operations["delete_conversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /v1/conversations/{id}/turns` — append a user turn, run the bound
         *     provider, and return (or stream) the assistant turn, persisting both.
         */
        post: operations["create_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /v1/turns` — run the provider on a fully-inline conversation with **no**
         *     persistence. Shares [`execute_turn`] with the stateful path for parity.
         */
        post: operations["stateless_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /v1/usage` — tenant-scoped usage rollups grouped by key, model, or
         *     conversation, over an optional `[from, to]` time window.
         */
        get: operations["usage_rollup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /v1/whoami` — echoes the resolved [`TenantContext`]. Useful for smoke
         *     tests of the auth layer.
         */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Per-status item counts in a batch response. */
        BatchCountsDto: {
            /**
             * Format: int32
             * @description Items that were canceled.
             */
            canceled: number;
            /**
             * Format: int32
             * @description Items that failed.
             */
            errored: number;
            /**
             * Format: int32
             * @description Items that expired.
             */
            expired: number;
            /**
             * Format: int32
             * @description Items still being processed.
             */
            processing: number;
            /**
             * Format: int32
             * @description Items that completed successfully.
             */
            succeeded: number;
        };
        /**
         * @description One item of a batch create request: the inline stateless-turn shape plus an
         *     optional caller correlation id.
         */
        BatchItemInput: {
            /**
             * @description A caller-facing correlation id, unique within the batch. Defaults to
             *     `item-{index}` when omitted.
             */
            custom_id?: string | null;
            /** @description The full, inline message history to run. */
            messages: Record<string, never>[];
            /** @description The model identifier, as the provider expects it. */
            model: string;
            /** @description Request-time provider options. */
            options?: Record<string, never> | null;
            /** @description The provider to run against (e.g. `"anthropic"`). */
            provider: string;
            /** @description An optional system prompt. */
            system?: string | null;
            /** @description An optional prompt-cache breakpoint on the system prompt. */
            system_cache?: Record<string, never> | null;
        };
        /** @description A batch job as returned by the API. */
        BatchJobDto: {
            /** @description Per-status item counts. */
            counts: components["schemas"]["BatchCountsDto"];
            /**
             * Format: date-time
             * @description When the job was created.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the job ended, if it has.
             */
            ended_at?: string | null;
            /** @description The last transient provider/poll error, if any. */
            error?: string | null;
            /**
             * Format: uuid
             * @description The job id.
             */
            id: string;
            /** @description The provider the job runs against. */
            provider: string;
            /** @description The provider-native batch id, once submitted. */
            provider_batch_id?: string | null;
            /**
             * @description The lifecycle status (`created`, `submitting`, `in_progress`,
             *     `canceling`, `ended`).
             */
            status: string;
            /**
             * Format: int32
             * @description The total number of items.
             */
            total_items: number;
            /**
             * Format: date-time
             * @description When the job was last updated.
             */
            updated_at: string;
        };
        /** @description Request body for creating a batch. */
        CreateBatchRequest: {
            /** @description The batch's items, in submission order. */
            items: components["schemas"]["BatchItemInput"][];
        };
        /** @description Request body for creating a conversation. */
        CreateConversationRequest: {
            /** @description Free-form caller metadata (tags, correlation IDs, …). */
            metadata?: Record<string, never> | null;
            /** @description The model identifier, as the provider expects it. */
            model: string;
            /** @description The provider to bind the conversation to (e.g. `"anthropic"`). */
            provider: string;
            /** @description An optional system prompt applied to the whole conversation. */
            system?: string | null;
        };
        /**
         * @description Request body for a stateless turn: the whole conversation is supplied inline
         *     and nothing is persisted.
         */
        StatelessTurnRequest: {
            /** @description The full, inline message history to run. */
            messages: Record<string, never>[];
            /** @description The model identifier, as the provider expects it. */
            model: string;
            /** @description Request-time provider options. */
            options?: Record<string, never> | null;
            /** @description The provider to run against (e.g. `"anthropic"`). */
            provider: string;
            /** @description Whether to stream the assistant turn as Server-Sent Events. */
            stream?: boolean;
            /** @description An optional system prompt. */
            system?: string | null;
            /** @description An optional prompt-cache breakpoint on the system prompt. */
            system_cache?: Record<string, never> | null;
        };
        /** @description Request body for appending a turn to a stored conversation. */
        TurnRequest: {
            /** @description The user turn's content parts, in provider-significant order. */
            content: Record<string, never>[];
            /** @description Request-time provider options (sampling, tools, …). */
            options?: Record<string, never> | null;
            /** @description Whether to stream the assistant turn as Server-Sent Events. */
            stream?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBatchRequest"];
            };
        };
        responses: {
            /** @description Batch created (status = created) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid virtual key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Budget exceeded (block action) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Capability unsupported or provider not configured */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_batch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Batch id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The batch status and counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No such batch for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    cancel_batch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Batch id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The batch, transitioned toward cancellation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No such batch for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_batch_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Batch id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSONL stream, one result object per line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description No such batch for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid virtual key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_conversation: {
        parameters: {
            query?: {
                /** @description Max messages to return (default 100) */
                limit?: number;
                /** @description Messages to skip from the start */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Conversation id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation and a page of its messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No such conversation for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such conversation for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description The assistant message, or an SSE stream when stream=true */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No such conversation for this tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Capability unsupported or provider not configured */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    stateless_turn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatelessTurnRequest"];
            };
        };
        responses: {
            /** @description The assistant message, or an SSE stream when stream=true */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Capability unsupported or provider not configured */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    usage_rollup: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound (RFC 3339) */
                from?: string;
                /** @description Inclusive upper bound (RFC 3339) */
                to?: string;
                /** @description key | model | conversation (default model) */
                group_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped token and cost rollups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Invalid group_by or time bound */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid virtual key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated tenant identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid virtual key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
