//! Token- and tool-usage accounting.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A snapshot of the resource usage a provider reported for a response.
///
/// Every token-count field is optional because not all providers report every
/// figure, and the distinction between "reported as zero" and "not reported"
/// is meaningful for billing and attribution. The provider's raw usage payload
/// is preserved verbatim in [`Usage::raw`] so that no provider-specific figure
/// is ever lost.
///
/// The type is `#[non_exhaustive]`: providers may expose additional usage
/// dimensions over time.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Usage {
    /// Input (prompt) tokens billed at the full rate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<u64>,

    /// Output (completion) tokens generated by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<u64>,

    /// Input tokens served from the provider's prompt cache (billed at a
    /// reduced rate).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<u64>,

    /// Input tokens written to the provider's prompt cache (billed at a
    /// premium rate).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<u64>,

    /// Per-tool invocation counts for provider-executed (server-side) tools,
    /// keyed by the provider's usage field name (e.g.
    /// `"web_search_requests"`).
    ///
    /// A [`BTreeMap`] is used so serialization is deterministic. Empty when the
    /// response used no server tools.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub server_tool_use: BTreeMap<String, u64>,

    /// The provider's raw usage payload, preserved verbatim so that no
    /// provider-specific figure is dropped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<serde_json::Value>,
}

impl Usage {
    /// Constructs an empty [`Usage`] with every field unset.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }
}
